name: Atualizar Dados DSS

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Executar script
        run: python atualizar.py

      - name: Commit das alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add dados.json

          git diff --cached --quiet || git commit -m "Atualização automática do DSS"

          git push
